### ISSUE TITLE
global owner commands

### ISSUE THREAD

**Issue by rinzes** [andreimarcu/aamnews#21]
I have the following in the config.py:

admins = owner = dutch
owner_host = "my ip address"

after I connect I msg the bot .add_channel "#channelname" 0

and I get back:

<aanews> Command is global owner only.

what am I doing wrong

**Comment by andreimarcu** [comment]
I'm guessing you meant 
`admins = owner = 'dutch'`  
But just in case, connect to irc and check that your host mask is exactly your ip and not dns

**Comment by rinzes** [comment]
I understand now...
